itdelatrisu/opsu

src/org/newdawn/slick/openal/Mp3InputStream.java
src/org/newdawn/slick/openal/OpenALStreamPlayer.java
src/org/newdawn/slick/openal/SoundStore.java

Close file handles so files can be deleted.
Not sure if this fixed the memory leak.

close mp3 file handles.

---

src/itdelatrisu/opsu/audio/HitSound.java
src/itdelatrisu/opsu/audio/MultiClip.java
src/itdelatrisu/opsu/audio/SoundController.java
src/itdelatrisu/opsu/audio/SoundEffect.java
src/itdelatrisu/opsu/states/GameRanking.java

This might fix some issues with some sounds not being played sometimes.
Also might require more memory since more clips are created.

Allows multiple instance of the same clip to be played simultaneously.

---

src/itdelatrisu/opsu/Options.java
src/itdelatrisu/opsu/states/OptionsMenu.java

I use the comma and period keys to click with. Since I have the tablet directly in front of my keyboard, that stops me from having to reach all the way over to the z/x keys which would be quite uncomfortable.
There's no reason why someone can't have ctrl/alt or home/pgup as their preferred keys either. At the moment I think just escape needs to be checked for to make this "idiot proof", but I would question the usefulness of idiot-proofing to that degree. I've done it anyway.

Remove restriction from left/right click keys

---

src/itdelatrisu/opsu/OsuHitObject.java
src/itdelatrisu/opsu/Utils.java
src/itdelatrisu/opsu/objects/Circle.java
src/itdelatrisu/opsu/objects/DummyObject.java
src/itdelatrisu/opsu/objects/HitObject.java
src/itdelatrisu/opsu/objects/Slider.java
src/itdelatrisu/opsu/objects/Spinner.java
src/itdelatrisu/opsu/states/Game.java

Move slider.sliderTime calculation from update() to constructor. Necessarily for slider.getPointAt() to work properly.
To order to get accurate slider end position, need access to both HitObject and OsuHitObject at same time.
HitObject.updatePosition() is a workaround since we can't calculate stack when hit object initializates.
Algorithm is pretty solid. Some numbers (STACK_LENIENCE, STACK_TIMEOUT, stackModifier etc) can be a little bit off.

Hit object stacking algorithm

---

src/itdelatrisu/opsu/Container.java
src/itdelatrisu/opsu/render/CurveRenderState.java
src/itdelatrisu/opsu/render/FrameBufferCache.java
src/itdelatrisu/opsu/render/Rendertarget.java

related to #101
Correctly clean up the created OpenGL objects created for the slider rendering.
This is necessary because the OpenGL context being closed does apparently not close
the process and the game can be restarted with another resolution without shutting
down the process completely.
Not really sure what else to do to cleanly shut this down, I'll add some more comments in a moment

Fullscreen resizing fix 

---

src/itdelatrisu/opsu/render/CurveRenderState.java
src/itdelatrisu/opsu/render/Rendertarget.java

Backup and restore the viewport size when rendering sliders. Needed because Slick tends to allocate offscreen buffers for itself only with power of two textures, so it will use another viewport when rendering to its own offscreen buffers.
Should fix #107

Backup and restore the viewport size when rendering sliders

---

src/itdelatrisu/opsu/objects/curves/Curve.java
src/itdelatrisu/opsu/states/MainMenu.java
src/org/newdawn/slick/Input.java

Various bug fixes

---

.gitignore
src/itdelatrisu/opsu/GameMod.java
src/itdelatrisu/opsu/objects/Circle.java
src/itdelatrisu/opsu/objects/Slider.java
src/itdelatrisu/opsu/objects/Spinner.java
src/itdelatrisu/opsu/states/Game.java

Enables the 'hidden' game-mod and changes circles and sliders accordingly.

'Hidden' gamemod

---

src/itdelatrisu/opsu/objects/curves/Curve.java
src/itdelatrisu/opsu/render/CurveRenderState.java

I didn't really use any of the newer features anyway.
This should accomodate open source drivers that use older versions of MESA.
Related to #120

Lower GLSL version requirement

---

src/itdelatrisu/opsu/objects/curves/Curve.java
src/itdelatrisu/opsu/render/CurveRenderState.java

For poor guys with eg. old intel gma mobile gpus.

Rewrote shaders for GLSL 110 (openGL2.0).

---

build.gradle

I've found no way to access it without this workaround: https://discuss.gradle.org/t/can-i-override-the-group-property-from-the-command-line/5294
It's now possible to build with `gradle jar -PXDG=true`.

Make the XDG-option available from command line

---

src/itdelatrisu/opsu/GameData.java
src/itdelatrisu/opsu/Options.java
src/itdelatrisu/opsu/objects/Slider.java
src/itdelatrisu/opsu/objects/curves/Curve.java
src/itdelatrisu/opsu/render/CurveRenderState.java
src/itdelatrisu/opsu/render/Rendertarget.java
src/itdelatrisu/opsu/states/OptionsMenu.java

regarding #133 
Not ready for merging yet (mmsliders needs to be optimized). This is mainly for discussion around things like the pop-in of "repeat" arrows and other complications.
Draws curves in a range from 0 to x (where x is a value between 0 and 1), instead of always drawing the full curve

Snaking sliders initial implementation.

---

src/itdelatrisu/opsu/GameData.java
src/itdelatrisu/opsu/objects/curves/Curve.java
src/itdelatrisu/opsu/render/CurveRenderState.java

The old code created a framebuffer for every slider drawn, which results in a major performance loss, especially on shared memory systems like integrated GPUs.
The new codes renders a 'ramp', not individual cones, so the sliders look extra smooth.
Also, there is no framebuffer involved, meaning the new sliders can be used on more systems.

Improve slider rendering.

---

src/itdelatrisu/opsu/GameData.java
src/itdelatrisu/opsu/objects/Slider.java

Slider improvements (hidden, followcircle, ticks, reversearrow)

---

src/itdelatrisu/opsu/Options.java
src/itdelatrisu/opsu/audio/MusicController.java
src/itdelatrisu/opsu/beatmap/BeatmapParser.java
src/itdelatrisu/opsu/states/MainMenu.java
src/itdelatrisu/opsu/states/SongMenu.java
src/itdelatrisu/opsu/ui/Colors.java
src/itdelatrisu/opsu/ui/MenuButton.java

close #163 when merged
I made it pulse at 1Hz when music is paused, which may look a bit weird with the scaling. Adjust if needed.

Pulse main menu logo to the beat, add pulsing logo in song menu

---

src/itdelatrisu/opsu/GameData.java

Animate the score display in the ranking screen, finishing when the white flash appears. It displays the correct digits from left to right in equal time intervals, filling the rest of the digits with random digits.
This is for parity with osu!.
See also #231.

Animate score display in the ranking screen

---

src/itdelatrisu/opsu/ui/NotificationManager.java

Fixes #253
This approach is recommended in the docs:
https://docs.oracle.com/javase/7/docs/api/java/util/Collections.html#synchronizedList%28java.util.List%29

Synchronize notifications list access

---

src/itdelatrisu/opsu/options/Options.java
src/itdelatrisu/opsu/options/OptionsOverlay.java

Add a new method `isRestartRequired` to the `GameOption` enum that returns `true` if the option requires a restart to take effect. The method returns `false` by default and the option should override this if `true` is needed. This approach is less messy than adding a flag to the various constructors.
The restart button was previously not shown for the following options:
- `DISABLE_SOUNDS`
- `ENABLE_WATCH_SERVICE`
The restart button continues to be shown for the following options:
- `SCREEN_RESOLUTION`
- `FULLSCREEN`
- `SKIN`

Show restart button for options that require a restart

---

src/itdelatrisu/opsu/objects/Slider.java

Fix snaking sliders not snaking with regular sliders (introduced by 0ad8291). This was a logic error.
isCurveCompletelyDrawn <==> (snaking => alpha == 1)
"The curve is completely drawn if and only if snaking implies alpha = 1".
A implies B is the same as (NOT A) OR B.
Fixes #286

Fix regular snaking sliders

---

src/itdelatrisu/opsu/objects/Slider.java

Slidercaps are being draw on the initial circle when experimental sliders are enabled while the slider caps option is disabled (blame 0ad8291 from pull request #263).
Incorrect behavior can be easily seen on the osu! tutorial map on every slider with reverse arrows. 
The commit inside this pull request fixes that.

fix slidercaps being drawn when they shouldn't

---

src/itdelatrisu/opsu/beatmap/Beatmap.java
src/itdelatrisu/opsu/states/MainMenu.java
src/itdelatrisu/opsu/states/SongMenu.java

Updates the display on the song and main menus to display where the audio came from (e.g. `東方Project`, `Nico Nico Douga`, `ラブライブ! School idol project` etc.)
Expect use of Unicode characters as `beatmap.source` is not limited to English.

Display beatmap's source on song select

---

src/itdelatrisu/opsu/skins/SkinLoader.java

Some skins, notably manually edited ones, include spaces in the RGB color values, which causes the integer parse command to fail as it cannot recognize whitespace as a valid number.
This should now be able to read RGB values with spaces, for example: `Combo3 : 255, 121, 198` and treat it the same way as `Combo3: 255,121,198`

Trim whitespace in skin color parsing

---

.editorconfig

[EditorConfig](http://editorconfig.org/) allows [supporting editors](http://editorconfig.org/#download) to automatically adjust their settings, most significantly in our case the use of tabs instead of spaces for indentation.
I would have included `end_of_line=lf`, but not all files in the project have LF line endings. The following have CRLF line endings:
```
$ find src -name '*.java' -exec file {} \; | grep CRLF | cut -f 1 -d :
src/itdelatrisu/opsu/audio/MultiClip.java
src/itdelatrisu/opsu/objects/curves/CatmullCurve.java
src/itdelatrisu/opsu/objects/curves/CentripetalCatmullRom.java
src/itdelatrisu/opsu/objects/curves/CurveType.java
src/itdelatrisu/opsu/objects/curves/EqualDistanceMultiCurve.java
src/itdelatrisu/opsu/replay/ReplayImporter.java …
```

Add an EditorConfig

---

src/itdelatrisu/opsu/audio/MultiClip.java
src/itdelatrisu/opsu/audio/SoundController.java

Needs more testing on other setups.
Adds more details with issues regarding sound file loading and possibly fix the Linux side of `LineUnavailableException`s.
Has been tested on Windows (`Windows 10 x64`) and Linux (`Mint Cinnamon 18.3 x64`) with no ill effects.
- Don't open a line with the same format twice (as found in [this StackOverflow post](https://stackoverflow.com/questions/11915469/java-sound-format-not-supported))
- Add an additional catch clause for `UnsupportedAudioFileException` to better distinguish audio file-specific errors (such as corrupted files) and more general errors (such as non-present decoders for an audio type)

Add catch clause for UnsupportedAudioFileException and fix LineUnavailableExceptions 

---

src/itdelatrisu/opsu/states/ButtonMenu.java

Adding this gives us a reliable, cross-platform way of getting this info for issues that don't already have it.
I went with the clipboard implementation because it was the simplest to implement and it would be the most likely use case.
Resolves #374

Add About entry to copy debug info

---

src/itdelatrisu/opsu/states/Game.java

fixes issue #401 (minus the stack leniency calculations) caused by the cursor trail taking a very long time to draw, caused by autopoint being at infinity coordinates, caused by a division by zero caused by one hitobject's start time being the same as the previous hitobject's end time.
I've added an explicit check for `0`. Clamping the  `t` value between `[0, 1]` would've also fixed it, but I don't think that's necessary.

fix near-infinite loop on certain 2B maps
